import { chromium, devices } from 'playwright';
const b = await chromium.launch();
const c1 = await b.newContext({ viewport:{width:1440,height:900}, reducedMotion:'reduce' });
const p1 = await c1.newPage();
await p1.goto('http://localhost:4747/#/seventh'); await p1.waitForTimeout(2500);
await p1.mouse.move(900,400); await p1.waitForTimeout(600);
await p1.screenshot({path:'capture/crit-7/a11y-reduced.png'});
await p1.keyboard.press('Escape'); await p1.waitForTimeout(1600);
console.log('ESC ->', p1.url());
await p1.screenshot({path:'capture/crit-7/a11y-esc.png'});
const c2 = await b.newContext({ ...devices['iPhone 13'] });
const p2 = await c2.newPage();
const errs=[]; p2.on('pageerror',e=>errs.push(''+e));
await p2.goto('http://localhost:4747/#/seventh'); await p2.waitForTimeout(2500);
await p2.screenshot({path:'capture/crit-7/a11y-touch-0.png'});
const vp = p2.viewportSize();
await p2.touchscreen.tap(Math.round(vp.width*0.45), Math.round(vp.height*0.6));
await p2.waitForTimeout(900);
await p2.screenshot({path:'capture/crit-7/a11y-touch-1.png'});
console.log('touch errors', errs);
await b.close();
